import './blocks/accordion_element/index.scss';
import './blocks/button/index.scss';
import './blocks/buttons/index.scss';
import './blocks/cta/index.scss';
import './blocks/four-column/index.scss';
import './blocks/three-column/index.scss';
import './blocks/two-column-text/index.scss';
import './blocks/two-tile/index.scss';
import './blocks/blocks.scss';
